service: slack-channel-messages
# frameworkVersion: "4"
provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_APP_TOKEN: ${env:SLACK_APP_TOKEN}
    MONGO_DB_URL: ${env:MONGO_DB_URL}
    FINANCE_CHANNEL_ID: ${env:FINANCE_CHANNEL_ID}
    SUPPORT_CHANNEL_ID: ${env:SUPPORT_CHANNEL_ID}
functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline
